import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // 自动生成侧边栏，根据文件夹结构
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // 从 docs 根目录开始生成
    },
  ],
  "前端技术": [
    {
      type: "category",
      label: "前端技术",
      link: {
        type: "generated-index",
      },
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "前端技术", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],
  "3D": [
    {
      type: "category",
      label: "3D",
      link: {
        type: "generated-index",
      },
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "3D", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],
  Web3: [{
    type: "category",
    label: "Web3",
    link: {
      type: "generated-index",
    },
    collapsible: false,
    items: [
      {
        type: "autogenerated",
        dirName: "Web3", // '.' 即当前的文档文件夹
      },
    ],
  }],
  AI: [{
    type: "category",
    label: "AI",
    link: {
      type: "generated-index",
    },
    collapsible: false,
    items: [
      {
        type: "autogenerated",
        dirName: "AI", // '.' 即当前的文档文件夹
      },
    ],
  }],
  跨平台: [{
    type: "category",
    label: "跨平台",
    link: {
      type: "generated-index",
    },
    collapsible: false,
    items: [
      {
        type: "autogenerated",
        dirName: "跨平台", // '.' 即当前的文档文件夹
      },
    ],
  }]
};

export default sidebars;
