import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // 自动生成侧边栏，根据文件夹结构
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // 从 docs 根目录开始生成
    },
  ],

  "前端技术": [
    {
      type: "category",
      label: "前端技术",
      link: {
        type: "generated-index",
      },
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "前端技术", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],
  "3D": [
    {
      type: "category",
      label: "3D",
      link: {
        type: "generated-index",
      },
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "3D", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],

  Web3: [{
    type: "category",
    label: "Web3",
    link: {
      type: "generated-index",
    },
    collapsible: false,
    items: [
      {
        type: "autogenerated",
        dirName: "Web3", // '.' 即当前的文档文件夹
      },
    ],
  }],

  AI和智能化: [{
    type: "category",
    label: "AI和智能化",
    link: {
      type: "generated-index",
    },
    collapsible: false,
    items: [
      {
        type: "autogenerated",
        dirName: "AI和智能化", // '.' 即当前的文档文件夹
      },
    ],
  }],

  Others: [{
    type: "category",
    label: "Others",
    link: {
      type: "generated-index",
    },
    collapsible: false,
    items: [
      {
        type: "autogenerated",
        dirName: "Others", // '.' 即当前的文档文件夹
      },
    ],
  }]
};

export default sidebars;
